# WARNING - Generated by {fusen} from /dev/flat_leaflet.polygonstyler.Rmd: do not edit by hand

#' setShapeLabel
#'
#' @param map map object
#' @param data data
#' @param layerId layerId
#' @param label label
#' @param options options
#'
#' @return leaflet map object
#' @importFrom leaflet getMapData filterNULL evalFormula invokeMethod
#' @export
#'
setShapeLabel <- function(map, data = getMapData(map), layerId,
                          label = NULL,
                          options = NULL) {
  options <- c(
    list(layerId = layerId),
    options,
    filterNULL(list(label = label))
  )
  # evaluate all options
  options <- evalFormula(options, data = data)
  # typo fixed in this line
  invokeMethod(map, data, "setLabel", "shape", layerId, label)
}
