# WARNING - Generated by {fusen} from /dev/flat_leaflet.polygonstyler.Rmd: do not edit by hand

#' setShapeStyle
#'
#' @param map map object
#' @param data data
#' @param layerId layerId
#' @param stroke stroke
#' @param color color
#' @param weight weight
#' @param opacity opacity
#' @param fill fill
#' @param fillColor fill color
#' @param fillOpacity fill opacity
#' @param dashArray dash array
#' @param smoothFactor smooth factor
#' @param noClip no clip
#' @param options options
#' @param label label
#'
#' @return
#' @importFrom leaflet evalFormula invokeMethod filterNULL getMapData
#' @export
#'
setShapeStyle <- function( map, data = getMapData(map), layerId,
                           stroke = NULL, color = NULL,
                           weight = NULL, opacity = NULL,
                           fill = NULL, fillColor = NULL,
                           fillOpacity = NULL, dashArray = NULL,
                           smoothFactor = NULL, noClip = NULL,
                           options = NULL, label = NULL
){
  options <- c(list(layerId = layerId),
               options,
               filterNULL(list(stroke = stroke, color = color,
                               weight = weight, opacity = opacity,
                               fill = fill, fillColor = fillColor,
                               fillOpacity = fillOpacity, dashArray = dashArray,
                               smoothFactor = smoothFactor, noClip = noClip, label = label
               )))
  options <- evalFormula(options, data = data)
  options <- do.call(data.frame, c(options, list(stringsAsFactors=FALSE)))
  
  layerId <- options[[1]]
  style <- options[-1] 
  
  invokeMethod(map, data, "setStyle", "shape", layerId, style);
}
